---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=600

- name: show apt list --upgradable
  shell: apt list --upgradable
  register: showAptListUpgradableOut

- debug:
    var: showAptListUpgradableOut.stdout_lines

- debug:
    msg: "You should send UPGRADE=1 enviroment variable to upgrade packages"
  when: lookup('env','UPGRADE') != '1'

- name: Upgrade APT to the latest packages
  apt: upgrade=dist
  register: apt_result
  when: lookup('env','UPGRADE') == '1'

- name: Autoremove unused packages
  command: apt-get -y autoremove
  register: apt_result
  changed_when: "'packages will be REMOVED' in apt_result.stdout"
  when: lookup('env','UPGRADE') == '1'

- name: Purge residual kernel packages
  shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
  register: apt_result
  changed_when: "'packages will be REMOVED' in apt_result.stdout"
  when: lookup('env','UPGRADE') == '1'
