---
- hosts: all
  tasks:
    - name: copy .tmux.conf to user home
      copy:
        src: /etc/ansible/configsToCopy/.tmux.conf
        dest: /home/{{ item }}/.tmux.conf
        owner: {{ item }}
        group: root
        mode: 0644
      with_items:
        - %USERNAME1%
