---
- name: "Uncomment strings for PgUp in /etc/inputrc"
  replace:
    dest: /etc/inputrc
    regexp: '(\s+)# "\\e\[5\~"\: history-search-backward(\s+.*)?$'
    replace: '\1"\\e[5~": history-search-backward\2'
- name: "Uncomment strings for PgDown in /etc/inputrc"
  replace:
    dest: /etc/inputrc
    regexp: '(\s+)# "\\e\[6\~"\: history-search-forward(\s+.*)?$'
    replace: '\1"\\e[6~": history-search-forward\2'
